REAGENT_STANDARD_REPLACEMENT = {
    "[Li]O": ["[Li+].[OH-]"],
    "CCCCCC.[Li]CCCC": ["CCCCCC", "[Li]CCCC"],
    "[Al+3].[H-].[H-].[H-].[H-].[Li+]": ["[AlH4-].[Li+]"],
    "CCCCCC.CCOCC": ["CCCCCC", "CCOCC"],
    "CC(=O)O.CO": ["CC(=O)O", "CO"],
    "C1CCCCC1.CCOC(C)=O": ["C1CCCCC1", "CCOC(C)=O"],
    "C1CCOC1.Cc1ccccc1": ["C1CCOC1", "Cc1ccccc1"],
    "CCO.COCCOC": ["CCO", "COCCOC"],
    "CCO.CCOC(C)=O": ["CCO", "CCOC(C)=O"],
    "C1CCOC1.ClCCl": ["C1CCOC1", "ClCCl"],
    "CCOC(C)=O.ClCCl": ["CCOC(C)=O", "ClCCl"],
    "CCO.ClCCl": ["CCO", "ClCCl"],
    "CN(C)C=O.ClCCl": ["CN(C)C=O", "ClCCl"],
    "C1CCOC1.CN(C)C=O": ["C1CCOC1", "CN(C)C=O"],
    "CC(C)=O.O=C=O": ["CC(C)=O", "O=C=O"],
    "CCO.Cc1ccccc1": ["CCO", "Cc1ccccc1"],
    "CCCCCCC.CCOC(C)=O": ["CCCCCCC", "CCOC(C)=O"],
    "C1CCOC1.CCO": ["C1CCOC1", "CCO"],
    "CCOC(C)=O.CO": ["CCOC(C)=O", "CO"],
    "CO.ClC(Cl)Cl": ["CO", "ClC(Cl)Cl"],
    "ClCCl.O=C(O)C(F)(F)F": ["ClCCl", "O=C(O)C(F)(F)F"],
    "CCCCCC.CCOC(C)=O": ["CCCCCC", "CCOC(C)=O"],
    "CO.ClCCl": ["CO", "ClCCl"],
    "C1CCOC1.CO": ["C1CCOC1", "CO"],
    "CCO.Cl": "CCO.Cl".split("."),
    "CCOC(C)=O.Cl": "CCOC(C)=O.Cl".split("."),
    "C1COCCO1.Cl": "C1COCCO1.Cl".split("."),
    "CO.Cl": "CO.Cl".split("."),
    "Br.CC(=O)O": "Br.CC(=O)O".split("."),
    "CO.N": "CO.N".split("."),
    "[Mn+4].[O-2].[O-2]": ["O=[Mn]=O"],
    "CO.C[O-].[Na+]": ["CO", "C[O-].[Na+]"],
    "CO[Na]": ["C[O-].[Na+]"],
    "CC(C)(C)O[Na]": ["CC(C)(C)[O-].[Na+]"],
    "CC(C)(C)O[K]": ["CC(C)(C)[O-].[K+]"],
    "CC(C)=O.O=S(=O)(O)O.O=[Cr](=O)=O": ["CC(C)=O", "O=S(=O)(O)O", "O=[Cr](=O)=O"],
    "[Cr+6].[O-2].[O-2].[O-2]": ["O=[Cr](=O)=O"],
    "CCN(CC)CC.Cc1ccccc1": "CCN(CC)CC.Cc1ccccc1".split("."),
    "C1CCOC1.CCCC[N+](CCCC)(CCCC)CCCC.[F-]": ["C1CCOC1", "CCCC[N+](CCCC)(CCCC)CCCC.[F-]"],
    "ClC(Cl)Cl.O=C(C=Cc1ccccc1)C=Cc1ccccc1.O=C(C=Cc1ccccc1)C=Cc1ccccc1.O=C(C=Cc1ccccc1)C=Cc1ccccc1.[Pd].[Pd]": [
        "ClC(Cl)Cl", "O=C(C=Cc1ccccc1)C=Cc1ccccc1.O=C(C=Cc1ccccc1)C=Cc1ccccc1.O=C(C=Cc1ccccc1)C=Cc1ccccc1.[Pd].[Pd]"],
    "[Pd].c1ccc(P(c2ccccc2)c2ccccc2)cc1.c1ccc(P(c2ccccc2)c2ccccc2)cc1.c1ccc(P(c2ccccc2)c2ccccc2)cc1.c1ccc(P(c2ccccc2)c2ccccc2)cc1": [
        "c1ccc([P](c2ccccc2)(c2ccccc2)[Pd]([P](c2ccccc2)(c2ccccc2)c2ccccc2)([P](c2ccccc2)(c2ccccc2)c2ccccc2)[P](c2ccccc2)(c2ccccc2)c2ccccc2)cc1"],
    "Cl[Pd]Cl.c1ccc(P(c2ccccc2)c2ccccc2)cc1.c1ccc(P(c2ccccc2)c2ccccc2)cc1": [
        "Cl[Pd](Cl)([P](c1ccccc1)(c1ccccc1)c1ccccc1)[P](c1ccccc1)(c1ccccc1)c1ccccc1"],
    "ClCCl.Cl[Pd]Cl.[Fe+2].c1ccc(P(c2ccccc2)[c-]2cccc2)cc1.c1ccc(P(c2ccccc2)[c-]2cccc2)cc1": ["ClCCl",
                                                                                              "Cl[Pd]Cl.[Fe+2].c1ccc(P(c2ccccc2)[c-]2cccc2)cc1.c1ccc(P(c2ccccc2)[c-]2cccc2)cc1"],
    "Cl[Pd]Cl.[CH]1[CH][CH][C](P(c2ccccc2)c2ccccc2)[CH]1.[CH]1[CH][CH][C](P(c2ccccc2)c2ccccc2)[CH]1.[Fe]": [
        "Cl[Pd]Cl.[Fe+2].c1ccc(P(c2ccccc2)[c-]2cccc2)cc1.c1ccc(P(c2ccccc2)[c-]2cccc2)cc1"],
    "[CH2-]CCC.[Li+]": ["[Li]CCCC"],
    "CC(C)NC(C)C.[Li]": ["CC(C)[N-]C(C)C.[Li+]"],
    "C[Si](C)(C)N[Si](C)(C)C.[Li]": ["C[Si](C)(C)[N-][Si](C)(C)C.[Li+]"],
    "CC(C)O[Ti](OC(C)C)(OC(C)C)OC(C)C": ["CC(C)[O-].CC(C)[O-].CC(C)[O-].CC(C)[O-].[Ti+4]"],
    "BrB(Br)Br.ClCCl": "BrB(Br)Br.ClCCl".split("."),
    "C1CCOC1.CC(C)O": "C1CCOC1.CC(C)O".split("."),
    "CCOCC.Cl": "CCOCC.Cl".split("."),
    "CC(=O)O.CC(=O)O.Ic1ccccc1": ["CC(=O)OI(OC(C)=O)c1ccccc1"],
    "CC(=O)O.CCO": "CC(=O)O.CCO".split("."),
    "CCCCCC.ClCCl": "CCCCCC.ClCCl".split("."),
    "C1CCOC1.CC(=O)O": "C1CCOC1.CC(=O)O".split("."),
    "CCOCC.ClCCl": "CCOCC.ClCCl".split("."),
    "C1CCOC1.CCCCCCC.CCc1ccccc1": "C1CCOC1.CCCCCCC.CCc1ccccc1".split("."),
    "C1CCOC1.C[Si](C)(C)[N-][Si](C)(C)C.[Li+]": ["C1CCOC1", "C[Si](C)(C)[N-][Si](C)(C)C.[Li+]"],
    "ClCCl.c1ccncc1": "ClCCl.c1ccncc1".split("."),
    "CCOC(C)=O.CCOCC": "CCOC(C)=O.CCOCC".split("."),
    "C1CCOC1.CCOC(C)=O": "C1CCOC1.CCOC(C)=O".split("."),
    "CO.CS(C)=O": "CO.CS(C)=O".split("."),
    "CC(C)[Mg]Cl.[Cl-].[Li+]": ["CC(C)[Mg]Cl", "[Cl-].[Li+]"],
    "C[Mg+].[Br-]": ["C[Mg]Br"],
    "CCOC(C)=O.Cc1ccccc1": "CCOC(C)=O.Cc1ccccc1".split("."),
    "C1CCOC1.CC#N": "C1CCOC1.CC#N".split("."),
    "CC#N.ClCCl": "CC#N.ClCCl".split("."),
    "C1COCCO1.CO": "C1COCCO1.CO".split("."),
    "COCCO[Al+]OCCOC.[H-].[H-].[Na+]": ["COCCO[AlH2-]OCCOC.[Na+]"],
    "CC(C)C[Al+]CC(C)C.[H-]": ["CC(C)C[AlH]CC(C)C"],
    "B.C1CCOC1": "B.C1CCOC1".split("."),
    "B#B": ["B"],
    "B.[Na]": ["[BH4-].[Na+]"]
}
